id: P010589
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS16692
  title: རྡོ་རྗེ་སེམས་དཔའ་ཐུགས་ཀྱིས་སྒྲུབ་པའི་བསྙེན་སྒྲུབ་ཆོ་ག་རྣམ་གྲོལ་ལམ་བཟང་།
  author: ''
  volumes:
    a766682f859b4d06a1e94cc27785a8ba:
      image_group_id: I8LS16711
      title: ''
      volume_number: 1
      total_pages: 134
      base_file: v001.txt
